### PR TITLE
Final Release

### PR DESCRIPTION
**Pull request by ofarrero**
- Fix drop down menu to show group names instead of group ids
- Fix exam response servlet so that it ignore exam id in the enumeration
- Fix exams taken servlet so that it can find the exam and therefore display the users responses
- Add pie chart to exams to show percentage answers correct and incorrect on exams taken servlet
- Add chart to show student results on exam
- Add charts tests
- Fix styling
- Add templates for exams and groups
- Processing external test method

### CODE REVIEW

**Review by marvel308 — DISMISSED** [review]
This change deletes a bunch of tests. Is it covered somewhere else?

**Comment by ofarrero** [comment]
> This change deletes a bunch of tests. Is it covered somewhere else?

I made a pr to add them back in must have forgot to merge it

**Comment by ofarrero** [comment]
All the tests have been added to this dev branch so when merged the tests will be there

**Review by alexeyd — APPROVED** [review]

**Comment by AidanMolloy** [comment]
Must create a new run for checkstyle since it is exceeding character limits on examServlet directory

**Pull request merged**
